version: '3.1'
services:
  gesttrans_db:
    image: mysql:8.0.15
    restart: always
    environment:
      MYSQL_DATABASE: 'gesttrans'
        # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
        # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
        # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
        # <Port exposed> : < MySQL Port running inside container>
       - '3306:3306'
    expose:
        # Opens port 3306 on the container
      - '3306'
        # Where our data will be persisted


  mongodb:
    image: mongo:latest
    container_name: mongoTransportServer
    restart: always
    volumes:
      - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
      - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ./.docker/mongodb/data/db/:/data/db/
      - ./.docker/mongodb/data/log/:/var/log/mongodb/

    environment:
      MONGO_INITDB_DATABASE: gestionTransport
    ports:
      - 27017:27017