version: '3.1'
services:
  gesttrans_db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: gettrans
      MYSQL_USER: root
      MYSQL_PASSWORD: root123



  mongodb:
    image: mongo:latest
    container_name: mongoTransportServer
    restart: always
    volumes:
      - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
      - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ./.docker/mongodb/data/db/:/data/db/
      - ./.docker/mongodb/data/log/:/var/log/mongodb/

    environment:
      MONGO_INITDB_DATABASE: gestionTransport
    ports:
      - 27017:27017